name: "Build amd64"

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - "build-script/build.sh"


permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Run build scripts
        run: |
          sudo bash ./build-script/build.sh
      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-amd64-${{ env.dist_version }}
          name: Release amd64 ${{ env.dist_version }}
          files: |
            Devuan.zip
            rootfs.tar.gz
          preserve_order: true
          make_latest: false

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}