name: "Build arm64"

on:
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          sudo apt update && sudo apt install -yq curl unzip zip
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
          curl -L -o /tmp/devuankey.deb http://deb.devuan.org/merged/pool/DEVUAN/main/d/devuan-keyring/devuan-keyring_2025.08.09_all.deb
          sudo apt install -yq /tmp/devuankey.deb
      - name: Build rootfs
        run: |
          dist_version="$RELEASE"
          sudo mmdebstrap \
          --arch=arm64 \
          --variant=minbase \
          --components="main,contrib,non-free" \
          --include=ca-certificates,locales,devuan-keyring \
          --format=tar \
          ${dist_version} \
          - \
          "deb http://deb.devuan.org/merged ${dist_version} main contrib non-free" \
          "deb http://deb.devuan.org/merged ${dist_version}-updates main contrib non-free" \
          "deb http://deb.devuan.org/merged ${dist_version}-security main contrib non-free" \
          | xz -9 -T0 -c > rootfs.tar.gz

      - name: Combine wsldl and rootfs
        run: |
          curl -L https://github.com/yuk7/wsldl/releases/download/26032000/icons_arm64.zip -o icons.zip
          unzip icons.zip
          zip Devuan.zip rootfs.tar.gz devuan.exe
      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ env.RELEASE }}
          name: Release arm64 ${{ env.RELEASE }}
          files: |
            Devuan.zip
          preserve_order: true
          make_latest: false

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE: excalibur